using Arniston_Letting_API.Data;
using Arniston_Letting_API.DTOs.Reports;
using Arniston_Letting_API.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Arniston_Letting_API.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class ReportsController : ControllerBase
{
    private readonly ApplicationDbContext _context;

    public ReportsController(ApplicationDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<ReportDto>>> GetReports()
    {
        var reports = await _context.Reports
            .AsNoTracking()
            .Select(r => new ReportDto
            {
                ReportId = r.ReportId,
                ReportType = r.ReportType,
                Date = r.Date,
                GeneratedBy = r.GeneratedBy,
                Status = r.Status,
                Description = r.Description
            })
            .OrderByDescending(r => r.Date)
            .ToListAsync();

        return Ok(reports);
    }

    [HttpGet("{id:int}")]
    public async Task<ActionResult<ReportDto>> GetReport(int id)
    {
        var report = await _context.Reports
            .AsNoTracking()
            .Where(r => r.ReportId == id)
            .Select(r => new ReportDto
            {
                ReportId = r.ReportId,
                ReportType = r.ReportType,
                Date = r.Date,
                GeneratedBy = r.GeneratedBy,
                Status = r.Status,
                Description = r.Description
            })
            .FirstOrDefaultAsync();

        if (report == null)
        {
            return NotFound(new
            {
                message = "Report not found."
            });
        }

        return Ok(report);
    }

    [HttpPost]
    [Authorize(Roles = "Admin")]
    public async Task<ActionResult<ReportDto>> CreateReport(
        [FromBody] CreateReportDto request)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var reportType = request.ReportType?.Trim();
        var generatedBy = request.GeneratedBy?.Trim();
        var status = request.Status?.Trim();
        var description = request.Description?.Trim();

        if (string.IsNullOrWhiteSpace(reportType))
        {
            return BadRequest(new
            {
                message = "Report type is required."
            });
        }

        if (string.IsNullOrWhiteSpace(generatedBy))
        {
            return BadRequest(new
            {
                message = "Generated by is required."
            });
        }

        if (string.IsNullOrWhiteSpace(status))
        {
            return BadRequest(new
            {
                message = "Report status is required."
            });
        }

        var report = new Report
        {
            ReportType = reportType,
            Date = request.Date,
            GeneratedBy = generatedBy,
            Status = status,
            Description = description
        };

        _context.Reports.Add(report);

        await _context.SaveChangesAsync();

        var result = new ReportDto
        {
            ReportId = report.ReportId,
            ReportType = report.ReportType,
            Date = report.Date,
            GeneratedBy = report.GeneratedBy,
            Status = report.Status,
            Description = report.Description
        };

        return CreatedAtAction(
            nameof(GetReport),
            new { id = report.ReportId },
            result);
    }

    [HttpPut("{id:int}")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdateReport(
        int id,
        [FromBody] UpdateReportDto request)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var report = await _context.Reports
            .FirstOrDefaultAsync(r => r.ReportId == id);

        if (report == null)
        {
            return NotFound(new
            {
                message = "Report not found."
            });
        }

        var reportType = request.ReportType?.Trim();
        var generatedBy = request.GeneratedBy?.Trim();
        var status = request.Status?.Trim();
        var description = request.Description?.Trim();

        if (string.IsNullOrWhiteSpace(reportType))
        {
            return BadRequest(new
            {
                message = "Report type is required."
            });
        }

        if (string.IsNullOrWhiteSpace(generatedBy))
        {
            return BadRequest(new
            {
                message = "Generated by is required."
            });
        }

        if (string.IsNullOrWhiteSpace(status))
        {
            return BadRequest(new
            {
                message = "Report status is required."
            });
        }

        report.ReportType = reportType;
        report.Date = request.Date;
        report.GeneratedBy = generatedBy;
        report.Status = status;
        report.Description = description;

        await _context.SaveChangesAsync();

        return NoContent();
    }

    [HttpDelete("{id:int}")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DeleteReport(int id)
    {
        var report = await _context.Reports
            .FirstOrDefaultAsync(r => r.ReportId == id);

        if (report == null)
        {
            return NotFound(new
            {
                message = "Report not found."
            });
        }

        _context.Reports.Remove(report);

        await _context.SaveChangesAsync();

        return NoContent();
    }

    [HttpGet("{id:int}/generate")]
    public async Task<IActionResult> GenerateReport(int id)
    {
        var report = await _context.Reports
            .FirstOrDefaultAsync(r => r.ReportId == id);

        if (report == null)
        {
            return NotFound(new
            {
                message = "Report not found."
            });
        }

        report.Status = "Generated";
        report.Date = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        return Ok(new
        {
            report.ReportId,
            report.ReportType,
            report.Date,
            report.GeneratedBy,
            report.Status,
            report.Description
        });
    }
}